version: '3'
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    # volumes:
    #   - ./standalone-logs/:/home/nacos/logs
    #   - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - nacos
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ./env/mysql.env
    # volumes:
    #   - ./mysql:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: on-failure
    networks:
      - nacos

networks:
  nacos:
    driver: bridge
    name: nacos