version: '3'

services:
  redis:
    image: redis:5
    container_name: redis
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel verbose --requirepass nirvana
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local
    name: redis

networks:
  default:
    name: redis
    driver: bridge